name: Post Latest Blog from RSS to Bluesky

on:
  push:
    paths:
      - _posts/**
  workflow_dispatch:

jobs:
  fetch-and-post:
    runs-on: ubuntu-latest

    steps:
      # Optional small delay (helps feeds settle on fresh builds/CDNs)
      - name: Initial Delay
        run: |
          echo "Waiting for 1 minute before starting..."
          sleep 60

      - name: Install xmllint
        run: |
          sudo apt-get update && sudo apt-get install -y libxml2-utils

      - name: Fetch Latest Blog Post
        id: fetch_post
        shell: bash
        run: |
          set -euo pipefail

          RSS_FEED_URL="https://kyleboas.com/feed"
          response="$(curl -sfL "$RSS_FEED_URL")"

          title="$(echo "$response" | xmllint --xpath "string(//item[1]/title)" - | xargs)"
          url="$(echo "$response" | xmllint --xpath "string(//item[1]/link)" - | xargs)"
          pub_date_raw="$(echo "$response" | xmllint --xpath "string(//item[1]/pubDate)" - | xargs)"

          # Normalize both to YYYY-MM-DD
          pub_date_ymd="$(date -d "$pub_date_raw" +%Y-%m-%d || true)"
          today_ymd="$(date +%Y-%m-%d)"

          if [[ -z "$pub_date_ymd" ]]; then
            echo "Could not parse pubDate: '$pub_date_raw'. Skipping post."
            echo "should_post=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          if [[ "$pub_date_ymd" != "$today_ymd" ]]; then
            echo "Latest item is from $pub_date_ymd, not today ($today_ymd). Skipping post."
            echo "should_post=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          preview="$title $url"

          # Expose outputs (use heredoc for safety)
          {
            echo "should_post=true"
            echo "rss_url=$url"
            echo "preview<<EOF"
            echo "$preview"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Post to Bluesky
        if: steps.fetch_post.outputs.should_post == 'true'
        uses: myConsciousness/bluesky-post@v5
        with:
          text: ${{ steps.fetch_post.outputs.preview }}
          link-preview-url: ${{ steps.fetch_post.outputs.rss_url }}
          identifier: kyleboas.com
          password: ${{ secrets.BSS }}