name: Post Latest Blog from RSS to Bluesky

on:
  push:
    paths:
      - posts/**

jobs:
  fetch-and-post:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
         
      # Install dependencies
      - name: Install xmllint and dateutils
        run: |
          sudo apt-get update && sudo apt-get install -y libxml2-utils dateutils

      # Fetch the latest blog post from RSS feed
      - name: Fetch Latest Blog Post
        id: fetch_post
        run: |
          RSS_FEED_URL="https://kyleboas.com/feed"
          response=$(curl -s "$RSS_FEED_URL")
          description=$(echo "$response" | xmllint --xpath "string(//item[1]/description)" -)
          url=$(echo "$response" | xmllint --xpath "string(//item[1]/link)" -)
          pub_date=$(echo "$response" | xmllint --xpath "string(//item[1]/pubDate)" -)

          # Format dates for comparison
          pub_date_formatted=$(date -d "$pub_date" +"%Y-%m-%d")
          today=$(date +"%Y-%m-%d")

          if [[ "$pub_date_formatted" != "$today" ]]; then
            echo "The blog post was not published today. Exiting."
            exit 0
          fi

          # Prepare the message
          preview="$description $url"
          echo "preview=$preview" >> $GITHUB_ENV
          echo "rss_url=$url" >> $GITHUB_ENV

      # Post to Bluesky
      - name: Post to Bluesky
        uses: myConsciousness/bluesky-post@v5
        with:
          text: "${{ env.preview }}"
          link-preview-url: "${{ env.rss_url }}"
          identifier: kyleboas.com
          password: ${{ secrets.BSS }}