name: Schedule Posts

on:
  schedule:
    - cron: '30 7 * * *'  # 7:30
    - cron: '30 9 * * *'  # 9:30
    - cron: '30 11 * * *' # 11:30
    - cron: '30 13 * * *' # 13:30
    - cron: '30 15 * * *' # 15:30
    - cron: '30 17 * * *' # 17:30
    - cron: '30 19 * * *' # 19:30

jobs:
  curl: 
    runs-on: ubuntu-latest
    env:
      TZ: UTC
    steps:
      - name: Trigger GitHub Pages build
        uses: wei/curl@master
        with:
          args: "-X POST -H 'Authorization: token ${{ secrets.PAGES_ACCESS_TOKEN }}' -H 'Accept: application/vnd.github.ant-man-preview+json' https://api.github.com/repos/kyleboas/kyleboas.com/pages/builds"
